ID_PACIENTE INT PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
QUARTO_ID INT,
STATUS ENUM('Internado','Alta') NOT NULL
);

CREATE TABLE QUARTO (
ID_QUARTO INT PRIMARY KEY NOT NULL,
NUMERO INT NOT NULL,
TIPO ENUM('Enfermaria','Apartamento','UTI','Sala de Exame','Outro') NOT NULL
);

CREATE TABLE PEDIDO (
ID_PEDIDO INT PRIMARY KEY NOT NULL,
DATA_HORA DATETIME NOT NULL,
PACIENTE_ID INT,
QUARTO_ID INT,
STATUS ENUM('Em andamento','Entregue','Pago') NOT NULL
);

CREATE TABLE PRODUTO (
ID_PRODUTO INT PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL,
DESCRICAO TEXT,
PRECO DECIMAL(10,2) NOT NULL
);

CREATE TABLE PEDIDO_REALIZADO (
ID_ITEM_PEDIDO INT PRIMARY KEY NOT NULL,
PEDIDO_ID INT,
PRODUTO_ID INT,
QUANTIDADE INT NOT NULL,
VALOR_UNITARIO DECIMAL(10,2) NOT NULL
);

CREATE TABLE FATURA (
ID_FATURA INT PRIMARY KEY NOT NULL,
PACIENTE_ID INT,
VALOR_TOTAL DECIMAL(10,2) NOT NULL,
STATUS_PAGAMENTO ENUM('Pendente','Pago') NOT NULL,
DATA_PAGAMENTO DATETIME,
ID_METODO_PAGAMENTO INT
);

CREATE TABLE ENFERMEIRO (
CRE VARCHAR(10) PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL,
CARGO VARCHAR(50) NOT NULL,
SETOR VARCHAR(50) NOT NULL
);

CREATE TABLE METODO_PAGAMENTO (
ID_METODO_PAGAMENTO INT PRIMARY KEY NOT NULL,
TIPO ENUM('Cartão de Crédito','Cartão de Débito','Pix') NOT NULL,
DATA_HORA DATETIME NOT NULL
);

CREATE TABLE ENFERMEIRO_QUARTO_PERIODO (
ID_ENFERMEIRO_QUARTO_PERIODO INT PRIMARY KEY NOT NULL,
ENFERMEIRO_CRE VARCHAR(10),
QUARTO_ID INT,
DATA_INICIO DATETIME NOT NULL,
DATA_FIM DATETIME
);

ALTER TABLE PACIENTE ADD FOREIGN KEY (QUARTO_ID) REFERENCES QUARTO (ID_QUARTO);

ALTER TABLE PEDIDO ADD FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE (ID_PACIENTE);

ALTER TABLE PEDIDO ADD FOREIGN KEY (QUARTO_ID) REFERENCES QUARTO (ID_QUARTO);

ALTER TABLE PEDIDO_REALIZADO ADD FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO (ID_PEDIDO);

ALTER TABLE PEDIDO_REALIZADO ADD FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID_PRODUTO);

ALTER TABLE FATURA ADD FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE (ID_PACIENTE);

ALTER TABLE FATURA ADD FOREIGN KEY (ID_METODO_PAGAMENTO) REFERENCES METODO_PAGAMENTO (ID_METODO_PAGAMENTO);

ALTER TABLE ENFERMEIRO_QUARTO_PERIODO ADD FOREIGN KEY (ENFERMEIRO_CRE) REFERENCES ENFERMEIRO (CRE);

ALTER TABLE ENFERMEIRO_QUARTO_PERIODO ADD FOREIGN KEY (QUARTO_ID) REFERENCES QUARTO (ID_QUARTO);
